### ISSUE TITLE
doesn't work with python 3.x

### ISSUE THREAD

**Issue by Dalker** [JensErat/task-relative-recur#1] opened 2015-01-13 20:22 UTC
Just installed this, following the instructions from the readme. Then at the first invocation of `task # done` I got this message:

>  File "/home/dalker/.task/hooks/on-modify.relative-recur", line 23
>    print modified
>                 ^
> SyntaxError: Missing parentheses in call to 'print'

On my system, `python --version` outputs

> Python 3.4.2

This is solved by modifying the initial "shebang" line into

> # !/usr/bin/env python2

then it works.

(so this might not really be an issue, but more a notice to anyone who also has python 3 as default in their system - I don't know if "python2" is recognized in most systems to force the correct version nowadays, but it solved the issue in mine, however adding this little "2" might in fact cause problems in other systems...)

**Comment by JensErat** [comment] 2015-01-13 22:10
Thank you, I'll have a look at it in the next few days. If you have any other remarks or issues, please tell me. One small hint: I fixed an issue with taskwarrior's hooks and dates (dates being set do epoch 0 instead deleted if any hook is active), I'd recommend you to build the current 2.4.1 HEAD from git.

**Comment by Dalker** [comment] 2015-01-14 12:20
In fact with current TaskWarrior 2.4.0, your plugin does work as intended with relativeRecurDue:... and relativeRecurWait:... combined, but not with relativeRecurWait:... only, in which case the task is not repeated at all (at least on my system). I didn't try it with 2.4.1-git yet, though, so thanks for the tip! (and for the plugin!)

**Comment by JensErat** [comment] 2015-01-14 23:33
Indeed, there's something broken.

With the 2.4.0 release the plugin works as intended, but a seemingly unrelated issue occurs (https://bug.tasktools.org/browse/TW-1491). The patch I provided is already merged.

**Closed as completed** 2015-01-15 00:38 UTC

**Comment by JensErat** [comment] 2015-01-15 00:40
Went for making it compatible with both Python 2 and 3 instead of enforcing one of those versions, and fixed another bug on the go. Be welcome to report further issues or remarks if you have any.
